# CLI tools
brew "tmux"
brew "fzf"
brew "ripgrep"
brew "fd"
brew "lazygit"
brew "bat"
brew "stow"
brew "neovim"
brew "zsh-syntax-highlighting"
brew "fastfetch"
brew "golangci-lint"
brew "shellcheck"
brew "htop"
brew "tldr"
brew "tree"
brew "cmatrix"
brew "hadolint"
brew "lima"
brew "gh"

# Fonts
cask "font-jetbrains-mono-nerd-font"
cask "font-meslo-lg-nerd-font"

# GUI applications
cask "raycast"
