#!/usr/bin/env bash

# The script is executed as the user that triggered the configured Folder Action.
# The Folder Action is defined in the home directory of a user.

# The path to the file is passed
file="$1"
timestamp="$2"
dst="$HOME/Library/Mobile Documents/com~apple~CloudDocs/airdrop"

# If the file has no extended file attribute with this key, an error is printed
quarantineValue="$(xattr -p com.apple.quarantine "$file" 2>/dev/null)" || exit 1

# Extract the event identifier of the attribute value
eventIdentifier="$(echo "$quarantineValue" | awk -F';' 'NR==1 {print $4}')"

# Query the name of the agent for this event identifier from the quarantine database
agentName="$(
	sqlite3 "$HOME/Library/Preferences/com.apple.LaunchServices.QuarantineEventsV2" \
	"select LSQuarantineAgentName
	from LSQuarantineEvent
	where LSQuarantineEventIdentifier='$eventIdentifier';"
)"

# If the agent is sharingd, the file was received via AirDrop
if [[ "$agentName" == "sharingd" ]]; then
	mkdir -p "$dst"
	base="$(basename -- "$file")"
	name="${base%.*}"
	ext="${base##*.}"

	# using the timestamp method to prevent overwriting existing files (default of mv).
	# mv --backup is only available on Linux.
	# mv -n does not overwrite an existing file.
	# mv -i asks interactively to override (default no).
	# 'echo n | mv -i <src> <dst>' can read from stdin instead of interactive prompt.
	if [[ "$base" == "$ext" ]]; then
		mv -- "$file" "$dst/$base-air-$timestamp"
	else
		mv -- "$file" "$dst/$name-air-$timestamp.$ext"
	fi
else
	exit 1
fi
