#!/usr/bin/env bash

# This script executes AppleScript code.
# It creates a new iTerm2 window with the default profile but instead of the
# default login command "/bin/zsh" it is explicitly set in order to pass an env
# var. This env var is checked in the .zshrc file and tmux is only attached if
# this env var is not set. Therefore, in this case tmux is not executed because
# we use this window to call into the lima VM where tmux runs inside the VM.
# This solution with env var seems better than using the default command and then
# detach from tmux.
# The AppleScript code of this script is currently used as Shortcut "iterm2-open-vm".
#
# Resources: https://iterm2.com/documentation-scripting.html
# If --login is not used, there will be error message "podman not found"?

osascript <<EOF
tell application "iTerm2"
	activate
	set newWindow to (create window with default profile command "env NO_TMUX=1 /bin/zsh --login")
	tell current session of newWindow
		write text "lima"
	end tell
end tell
EOF
